# Generated by Django 4.0.7 on 2023-02-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_ad_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='text',
            field=models.TextField(max_length=5),
        ),
    ]
